# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: ğŸ Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: ğŸ“ˆ Build Snake Graph
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ŠğŸ¼ Checkout
        uses: actions/checkout@v2

      - name: ğŸ Generate snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: CruuzAzul
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: ğŸ—¿ Git status
        run: git status

      - name: ğŸ’ªğŸ¼ Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: ğŸªµ Output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
